# Generated by Django 2.2.5 on 2019-12-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='新闻id')),
                ('title', models.CharField(max_length=30, verbose_name='新闻标题')),
                ('add_time', models.CharField(max_length=30, verbose_name='新闻摘要')),
                ('click', models.IntegerField(verbose_name='点击次数')),
                ('img_url', models.CharField(max_length=30, verbose_name='标题图片')),
                ('content', models.TextField(verbose_name='新闻详情')),
            ],
            options={
                'verbose_name': '新闻列表',
                'verbose_name_plural': '新闻列表',
                'db_table': 'vue_news',
            },
        ),
    ]
