# Generated by Django 2.2.5 on 2019-12-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191215_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslist',
            name='zhaiyao',
            field=models.CharField(default='1', max_length=40, verbose_name='新闻摘要'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newslist',
            name='add_time',
            field=models.CharField(max_length=30, verbose_name='添加时间'),
        ),
    ]
