# Generated by Django 2.2.5 on 2019-12-15 07:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191215_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='评论人')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('content', models.CharField(max_length=120, verbose_name='评论内容')),
                ('n_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NewsList', verbose_name='所属新闻')),
            ],
            options={
                'verbose_name': '新闻评论',
                'verbose_name_plural': '新闻评论',
                'db_table': 'vue_news_comments',
            },
        ),
    ]
