# Generated by Django 2.2.5 on 2019-12-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_newscomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomments',
            name='content',
            field=models.CharField(max_length=500, verbose_name='评论内容'),
        ),
    ]
