# Generated by Django 2.2.5 on 2019-12-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191216_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturelist',
            name='img_url',
            field=models.CharField(max_length=150, verbose_name='展示图片'),
        ),
    ]
