# Generated by Django 2.2.5 on 2019-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191216_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturelist',
            name='seo_description',
            field=models.CharField(max_length=500, verbose_name='推广描述'),
        ),
    ]
