# Generated by Django 2.2.5 on 2019-12-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191216_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturelist',
            name='zhaiyao',
            field=models.CharField(max_length=500, verbose_name='摘要'),
        ),
    ]
