# Generated by Django 2.2.5 on 2019-12-17 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191216_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscomments',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AddField(
            model_name='newscomments',
            name='i_id',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, to='api.PictureList', verbose_name='所属图片'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='newscomments',
            table='vue_comments',
        ),
        migrations.DeleteModel(
            name='ImageComments',
        ),
    ]
