# Generated by Django 2.2.5 on 2019-12-17 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191217_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsSku',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('title', models.CharField(max_length=30, verbose_name='商品标题')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('zhaiyao', models.CharField(max_length=100, verbose_name='商品摘要')),
                ('click', models.CharField(max_length=10, verbose_name='点击次数')),
                ('img_url', models.CharField(max_length=50, verbose_name='显示图片')),
                ('sell_price', models.CharField(max_length=10, verbose_name='售卖价格')),
                ('market_price', models.CharField(max_length=10, verbose_name='之前价格')),
                ('stock_quantity', models.CharField(max_length=15, verbose_name='成交量')),
                ('goods_no', models.CharField(max_length=20, verbose_name='商品编号')),
                ('thum_img', models.CharField(max_length=200, verbose_name='缩略图')),
                ('content', models.TextField(verbose_name='商品详情页面')),
            ],
            options={
                'verbose_name': '商品列表',
                'verbose_name_plural': '商品列表',
                'db_table': 'vue_goods',
            },
        ),
        migrations.AlterModelOptions(
            name='newscomments',
            options={'verbose_name': '新闻评论', 'verbose_name_plural': '新闻评论'},
        ),
        migrations.RemoveField(
            model_name='newscomments',
            name='i_id',
        ),
        migrations.AlterModelTable(
            name='newscomments',
            table='vue_news_comments',
        ),
        migrations.CreateModel(
            name='ImageComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='评论人')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PictureList', verbose_name='所属图片')),
            ],
            options={
                'verbose_name': '图片评论',
                'verbose_name_plural': '图片评论',
                'db_table': 'vue_image_comments',
            },
        ),
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='评论人')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GoodsSku', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
                'db_table': 'vue_good_comments',
            },
        ),
    ]
