# Generated by Django 2.2.5 on 2019-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191217_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='img_url',
            field=models.CharField(max_length=100, verbose_name='显示图片'),
        ),
    ]
